feat(documentation): implement preface intro
DHBW-VS-WI17B/assignment-abe1-b1 pull request #11
Opened 2020-08-13 08:15 UTC by robingenz

2020-08-13 14:39 UTC, BohnetCarola reviewed
Im Rahmen dieser Seminararbeit wird ein Aktorensystem basierend auf der nachfolgenden Aufgabenstellung und den definierten Anforderungen sowie den Anwendungsfällen entwickelt und implementiert.

2020-08-14 14:19 UTC, BohnetCarola requested changes

2020-08-14 14:19 UTC, BohnetCarola commented on src/documentation/text/01_Preface/_intro.tex
> +Diese Arbeit dokumentiert den Entwurf und die Implementierung eines Aktorensystems der Gruppe B1 für die Veranstaltung \enquote{Angewandtes Business Engineering I}.
Im Rahmen dieser Seminararbeit wird ein Aktorensystem basierend auf der nachfolgenden Aufgabenstellung und den definierten Anforderungen sowie den Anwendungsfällen entwickelt und implementiert.

2020-08-14 14:19 UTC, robingenz commented on src/documentation/text/01_Preface/_intro.tex
> +Diese Arbeit dokumentiert den Entwurf und die Implementierung eines Aktorensystems der Gruppe B1 für die Veranstaltung \enquote{Angewandtes Business Engineering I}.
Mien Vorschlag: `Im Rahmen der Seminararbeit wird ein Aktorensystem, basierend auf der nachfolgenden Aufgabenstellung und den definierten Anforderungen, entworfen und implementiert.`

2020-08-14 14:30 UTC, ghost approved these changes

2020-08-14 14:31 UTC, BohnetCarola approved these changes

2020-08-14 14:34 UTC, merged