Update _intro.tex
DHBW-VS-WI17B/assignment-abe1-b1 pull request #15
Opened 2020-08-14 09:40 UTC by lucascheurer

Luca | UML Diagramm und Text, Tabellen fehlend

2020-08-15 10:00 UTC, ghost requested changes

2020-08-15 10:00 UTC, ghost commented on src/documentation/text/02_Use_cases/_intro.tex
> +Es dient der Beschreibung von elementaren Funktionen und \dfootcite[59]{objektorientierte_systemanalyse}{... stellt das Zusammenspiel der Anwendungsfälle eines Systems untereinander und mit den Akteu
schreibt man bei einem nicht vollständigen Zitat die Punkte nicht in eckige Klammern? "[...] stellt das Zusammenspiel der Anwendungsfälle eines Systems untereinander und mit den Akteuren dar"

2020-08-15 10:00 UTC, ghost commented on src/documentation/text/02_Use_cases/_intro.tex
> +Im Rahmen dieses Kapitels werden die funktionalen Anforderungen an das System in Form von Anwendungsfällen beschrieben.
Im Rahmen dieses Kapitels werden die in Kapitel 1.2 beschriebenen Anforderungen in Form von Anwendungsfällen beschrieben.

2020-08-16 08:47 UTC, ghost approved these changes

2020-08-16 08:51 UTC, BohnetCarola approved these changes

2020-08-16 08:52 UTC, robingenz approved these changes

2020-08-16 08:52 UTC, merged